networks:
  gg-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      gg-network:
        ipv4_address: 172.18.0.20
    hostname: frontend
    volumes:
      - ./Frontend:/app
      - gg-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: gg-nginx
    restart: unless-stopped
    networks:
      - gg-network
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:17.4-alpine
    container_name: gg-postgres
    restart: unless-stopped
    networks:
      gg-network:
        ipv4_address: 172.18.0.2
    env_file:
      - ./db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    build:
      context: ./DB
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: gg-db
    restart: unless-stopped
    networks:
      gg-network:
        ipv4_address: 172.18.0.3
    hostname: db
    depends_on:
      - postgres
    env_file:
      - ./.env

volumes:
  postgres_data:
    name: gg-postgres-data
  gg-node-modules:
    name: frontend-node-modules
